Repository cafeLogProject/backend, pull requests merged in 2025-01, with the labels that each got.

#32 feat: release-drafter test2
  src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
Labels: Feature

#33 refactor: release-drafter test
  src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
Labels: Refactor, ✨ patch

#35 refactor: release-drafter
  .github/release-drafter-config.yml
  .github/workflows/CICD-prod.yml
Labels: Refactor, ✨ patch

#39 feat: dasdadasadsasdassdaassdads
  src/main/java/cafeLogProject/cafeLog/api/favorite/dto/ToggleFavoriteReq.java
Labels: Feature, ✨ patch

#41 fix: 임시저장 리뷰 수정 api 버그 수정
  src/main/java/cafeLogProject/cafeLog/api/draftReview/dto/UpdateDraftReviewRequest.java
Labels: Feature

#44 fix: Return exception message instead of redirecting to login
  README.md
  src/main/java/cafeLogProject/cafeLog/common/auth/oauth2/CustomAuthenticationEntryPoint.java
  src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
  src/main/java/cafeLogProject/cafeLog/common/exception/GlobalExceptionHandler.java
Labels: Bug
