Repository cafeLogProject/backend, pull requests merged in 2025-02, with the labels that each got.

#47 fix: authenticationEntryPoint
  src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
Labels: Bug

#52 refactor: revert to the previous state
  .github/workflows/CI-prod.yml
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTFilter.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLoginHandler.java
  src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
Labels: Refactor

#49 feat: 임시저장 리뷰 단일/복수 삭제 api 추가, 테스트 추가, 그 외
  .github/workflows/CI-prod.yml
  .gitignore
  docker-compose-prod.yml
  src/main/java/cafeLogProject/cafeLog/api/draftReview/controller/DraftReviewController.java
  src/main/java/cafeLogProject/cafeLog/api/draftReview/dto/DeleteDraftReviewRequest.java
  src/main/java/cafeLogProject/cafeLog/api/draftReview/service/DraftReviewService.java
  src/main/java/cafeLogProject/cafeLog/api/image/service/DraftReviewImageService.java
  src/main/java/cafeLogProject/cafeLog/api/image/service/ReviewImageService.java
  src/main/java/cafeLogProject/cafeLog/api/review/service/ReviewService.java
  src/main/java/cafeLogProject/cafeLog/domains/image/util/ImageHandler.java
  src/main/resources/static/imgs/review/5e09c5d7-8ad1-474f-98d1-3c1a6363285a.webp
  src/test/java/cafeLogProject/cafeLog/CafeServiceTest.java
  src/test/java/cafeLogProject/cafeLog/ReviewServiceTest.java
  src/test/java/cafeLogProject/cafeLog/UserServiceTest.java
  src/test/java/cafeLogProject/cafeLog/service/draftReviewService/DeleteDraftReviewsAndImagesTest.java
  src/test/resources/application-test.yml
Labels: Feature

#54 fix: User NickName Duplicate Check
  docker-compose-prod.yml
  src/main/java/cafeLogProject/cafeLog/api/user/controller/UserController.java
  src/main/java/cafeLogProject/cafeLog/api/user/service/UserService.java
  src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
  src/main/java/cafeLogProject/cafeLog/domains/user/repository/UserRepository.java
  src/main/java/cafeLogProject/cafeLog/domains/user/repository/UserRepositoryCustom.java
  src/main/java/cafeLogProject/cafeLog/domains/user/repository/UserRepositoryImpl.java
  src/main/resources/application.yml
Labels: Bug

#56 refactor: Edit Cookie SameSite=None
  src/main/java/cafeLogProject/cafeLog/common/auth/common/CookieUtil.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTFilter.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLoginHandler.java
Labels: Refactor

#59 fix: Add server.tomcat.remoteip.portocol-header in application.yml
  src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: Bug

#62 feat: Add User Search By Nickname
  src/main/java/cafeLogProject/cafeLog/api/user/controller/UserController.java
  src/main/java/cafeLogProject/cafeLog/api/user/dto/UserSearchRes.java
  src/main/java/cafeLogProject/cafeLog/api/user/service/UserService.java
  src/main/java/cafeLogProject/cafeLog/common/exception/ErrorCode.java
  src/main/java/cafeLogProject/cafeLog/common/exception/user/UserNicknameNullException.java
  src/main/java/cafeLogProject/cafeLog/domains/user/repository/UserRepository.java
  src/main/java/cafeLogProject/cafeLog/domains/user/repository/UserRepositoryCustom.java
  src/main/java/cafeLogProject/cafeLog/domains/user/repository/UserRepositoryImpl.java
  src/main/resources/application.yml
Labels: Feature, ✨ minor

#63 feat: 특정 회원 리뷰 다수조회 api 추가, 외 버그 수정
  .gitignore
  src/main/java/cafeLogProject/cafeLog/api/review/controller/ReviewController.java
  src/main/java/cafeLogProject/cafeLog/api/review/dto/ShowUserReviewRequest.java
  src/main/java/cafeLogProject/cafeLog/api/review/service/ReviewService.java
  src/main/java/cafeLogProject/cafeLog/common/exception/GlobalExceptionHandler.java
  src/main/java/cafeLogProject/cafeLog/domains/review/repository/ReviewRepositoryCustomImpl.java
Labels: Bug, Feature

#66 fix: 메소드명 변경
  src/main/java/cafeLogProject/cafeLog/api/TestController.java
  src/main/java/cafeLogProject/cafeLog/domains/review/repository/ReviewRepositoryCustomImpl.java
Labels: enhancement

#70 fix: Implemented Redis caching for follow status
  src/main/java/cafeLogProject/cafeLog/common/config/RedisConfig.java
  src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
  src/main/java/cafeLogProject/cafeLog/common/exception/ErrorCode.java
  src/main/java/cafeLogProject/cafeLog/common/exception/FollowCursorException.java
  src/main/java/cafeLogProject/cafeLog/domains/follow/repository/FollowRepository.java
  src/main/java/cafeLogProject/cafeLog/domains/follow/repository/FollowRepositoryCustom.java
  src/main/java/cafeLogProject/cafeLog/domains/follow/repository/FollowRepositoryImpl.java
Labels: Bug

#78 fix: 이미지 조회 api 수정 : last modified 관련 304 버그 수정
  src/main/java/cafeLogProject/cafeLog/api/image/controller/DraftReviewImageController.java
  src/main/java/cafeLogProject/cafeLog/api/image/controller/ProfileImageController.java
  src/main/java/cafeLogProject/cafeLog/api/image/controller/ReviewImageController.java
  src/main/java/cafeLogProject/cafeLog/domains/image/util/ImageHandler.java
Labels: Bug

#79 refactor: JWT Token
  src/main/java/cafeLogProject/cafeLog/common/auth/AuthController.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTFilter.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLoginHandler.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLogoutFilter.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTLogoutHandler.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/JWTUtil.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/TokenExpiration.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/token/AccessRepository.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/token/AccessToken.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/token/JWTTokenService.java
  src/main/java/cafeLogProject/cafeLog/common/auth/jwt/token/RefreshRepository.java
  src/main/java/cafeLogProject/cafeLog/common/config/DevSecurityConfig.java
  src/main/java/cafeLogProject/cafeLog/common/config/RedisConfig.java
  src/main/java/cafeLogProject/cafeLog/common/config/SecurityConfig.java
  src/main/java/cafeLogProject/cafeLog/common/exception/GlobalExceptionHandler.java
Labels: Refactor
